In [19]:
import numpy as np
ar1=np.arange(13)
ar1
len(ar1)

13

In [7]:
#convert 1d into multidimensional array
reshaped_array=ar1.reshape(1,13)
reshaped_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [9]:
#identity matrix can be createdd using 2 functions
#eye()-->used to define both user defined rows and columns
#identity()-->used to define same number of rows and columns
#syntax-->np.identity(5)-->is 5 rows and 5 columns
#syntax-->np.eye(3,4)-->3 rows and 4 colums
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
#convert into complex
np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [21]:
#range of the array
ar2=np.arange(25)
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
#to perform multidimensional slicing
ar2=np.arange(25)
ar2.shape


(25,)

In [25]:
#to perform multidimensional slincing
ar2=np.arange(25).reshape(5,5)
ar2


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
#shape is consider as a property
ar2.shape

(5, 5)

In [29]:
#ar2[rows,colums,step]
#ar2[rows_start,row_end,column_start,column_end,step]
ar2[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [33]:
ar2[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [40]:
ar2[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
ar2[-3]

array([10, 11, 12, 13, 14])

In [47]:
#now reverse the values n becomes n-1 and n-1 becomes n 
ar2[-5:-3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
ar2[-2:-1,-2:-1]

array([[18]])

In [53]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [70]:
ar3=np.arange(50).reshape(5,10)
#tasks
#both positive and negative
#1.)print 27,28,37,38 
#2.)print 34,35,44,45
#3.)print 18,19
#4.)print 30,31,40,41

In [59]:
ar3=np.arange(50).reshape(5,10)
ar3


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
#to add based on column wise axis=0
np.sum(ar3,axis=0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [113]:
#1i)
ar3[2:4,7:9]


array([[27, 28],
       [37, 38]])

In [66]:
#to add based on row wise axis=1
np.sum(ar3,axis=1)

array([ 45, 145, 245, 345, 445])

In [68]:
#whole sum in matrix
np.sum(ar3)

1225

In [73]:
#mean-->average
#median-->centre value
#mode-->max num of repeated element
#variance-->median/tota num of elements
#std-->square root of variance

In [87]:
#1ii)
ar3[-3:-1,-3:-1]

array([[27, 28],
       [37, 38]])

In [79]:
#linespace():evenly separated
#linespace()
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [84]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [86]:
#linspace()
#it used to print the evenly separated pointed
#between 2 range of values
#-->linspace(start,end,num of values to be distributed)
np.linspace(1,10,4,dtype=int)

array([ 1,  4,  7, 10])

In [89]:
np.linspace(12,30)

array([12.        , 12.36734694, 12.73469388, 13.10204082, 13.46938776,
       13.83673469, 14.20408163, 14.57142857, 14.93877551, 15.30612245,
       15.67346939, 16.04081633, 16.40816327, 16.7755102 , 17.14285714,
       17.51020408, 17.87755102, 18.24489796, 18.6122449 , 18.97959184,
       19.34693878, 19.71428571, 20.08163265, 20.44897959, 20.81632653,
       21.18367347, 21.55102041, 21.91836735, 22.28571429, 22.65306122,
       23.02040816, 23.3877551 , 23.75510204, 24.12244898, 24.48979592,
       24.85714286, 25.2244898 , 25.59183673, 25.95918367, 26.32653061,
       26.69387755, 27.06122449, 27.42857143, 27.79591837, 28.16326531,
       28.53061224, 28.89795918, 29.26530612, 29.63265306, 30.        ])

In [91]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [93]:
#2i)
ar3[3:5,4:6]

array([[34, 35],
       [44, 45]])

In [97]:
#random module
#to generate random number between the range 
#np.random.randint(start,end)
np.random.randint(40)

31

In [99]:
np.random.randint(20,30)


21

In [101]:
np.random.randint(20,30,3)

array([27, 21, 29])

In [104]:
#rand()-->
#to get the randomly generated values from 0 to 1, based on uniform distribution
np.random.rand(4)


array([0.74756179, 0.10762867, 0.29234477, 0.39071498])

In [122]:
ar3[-3:-1,-6:-4]

array([[24, 25],
       [34, 35]])

#probability density function always have to be=1
#to find the area of rectangle=lenght*breadth
#to find the probability 

In [124]:
#rand()-->
#to get the randomly generated values from 0 to 1, based on normalised distribution
np.random.rand(3,4)

array([[0.20782976, 0.9970439 , 0.27850248, 0.49828061],
       [0.71907457, 0.77118131, 0.77948891, 0.60289877],
       [0.20915173, 0.14932557, 0.41583698, 0.81541389]])

In [126]:
#rand()-->
#to get the randomly generated values from 0 to 1, based on normalised distribution
np.random.randn(5)

array([-0.9655994 , -0.79268745, -1.1747476 ,  1.00229569,  1.30409502])

In [128]:
np.random.randn(5,4)

array([[ 1.31883676,  0.98605958, -0.4578474 ,  1.04733681],
       [-0.89331324, -0.6551369 , -0.64896119, -0.54854116],
       [ 0.98023981, -1.10221729, -0.63807342,  0.1430355 ],
       [-0.39458961, -0.13535633,  0.69133028, -1.11446077],
       [ 2.21103512,  0.83050904,  0.18899917,  1.76787501]])

In [130]:
ar3.min()

0

In [132]:
ar3.max()

49

In [134]:
#to find the index of min values
l1=[56,89,90,67,45]
print(l1.index(67))

3


In [136]:
print(ar3.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [139]:
print(ar3.argmin())

0


In [141]:
#to find the index of min values
l1=[56,89,90,67,45]
np1=np.array(l1)

In [143]:
#argmin()-->to find the min value index position in an array
print(np1.argmin())
#argmax()-->to find the max value index position in an array
print(np1.argmax())

4
2


In [145]:
np.sin(np1)
np.cos(np1)
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [147]:
1/np.sin(np1)

array([-1.91735803,  1.16269686,  1.11857241, -1.16887977,  1.17522136])

In [149]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [166]:
#task:1 ->write python code for the below logic
np2=np.array([1,2,3])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
#(1*4)+(2*5)+(3*6)=4+10+18=>32


In [155]:
sum=(np2[0]*np3[0])+(np2[1]*np3[1])+(np2[2]*np3[2])
print(sum)

32


In [157]:
np2=np.array([1,2,3,9])
np3=np.array([4,5,6])
sum=(np2[0]*np3[0])+(np2[1]*np3[1])+(np2[2]*np3[2])+(np2[3]*1)
print(sum)

41


In [160]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])
np2*np3

array([ 4, 10, 18])

In [164]:
fname=np.array(["sid","fn1","fn2"],dtype=str)
lname=np.array(['T',"ln1","ln2"],dtype=str)
#fname.tostring()
fname

array(['sid', 'fn1', 'fn2'], dtype='<U3')

In [172]:
#task: write python code to add below two arrays
np2=np.array([1,2,3,8,3,5,9])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3,1)
np.sum((np2*np3))
    

57

In [177]:
np1=np.array([1,34,56,78,np.nan,np.nan])
np1

array([ 1., 34., 56., 78., nan, nan])

In [179]:
#to print nan values
np1[np.isnan(np1)]

array([nan, nan])

In [181]:
#to element nan values
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [8]:
import numpy as np
np2=np.array([1,2,3])
np3=np.array([4,5,6])
np.dot(np2,np3)

32

In [9]:
#pandas

In [7]:
pip list panda

Package                       Version
----------------------------- ---------------
aiobotocore                   2.5.0
aiofiles                      22.1.0
aiohttp                       3.8.5
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
anaconda-anon-usage           0.4.2
anaconda-catalogs             0.2.0
anaconda-client               1.12.1
anaconda-cloud-auth           0.1.3
anaconda-navigator            2.5.0
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
async-timeout                 4.0.2
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8

In [10]:
#pandas
import pandas as pd
#pandas is deefined as open-source library that provides high-performance data manipulation in python
#data analysis requires lot of processing such as restructing,cleaning,mergin,manipulating,etc..we prefer padans to perform
#the above functionalities coz it is fast,simple than other tools
#pandas is built on numpy,numpy is required for operating pandas

In [11]:
#PANDAS SERIES:
#pandas series(labelled data)
#pandas series is a data structure with one dimensional labelled array
#it is a primary building block of dataframe,making its rows and columns

In [16]:
labels=['a','b','c']
my_data=[10,20,30]

arr=np.array(my_data)
d={'a':100,"b":200,"c":300}


In [18]:
#syntax-->pandas.Series(data=None,index=None,dtype=None,name=None,copy=True or False)
#Example
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [21]:
type(pd.Series(my_data))

pandas.core.series.Series

In [23]:
#Series with labels
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [25]:
#Series with labels
pd.Series(data=my_data,index=labels)
#    OR
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [27]:
pd.Series(data=[print,len,sum])

0    <built-in function print>
1      <built-in function len>
2      <built-in function sum>
dtype: object

In [29]:
pd.Series(data=[print(),len,sum])

0                       None
1    <built-in function len>
2    <built-in function sum>
dtype: object

In [32]:
class profile:
    @property
    def display(self):
        print("My name is sid")
p=profile()
p.display

My name is sid


In [35]:
def greet():
    return "good morning"
greet()

'good morning'

In [37]:
def greet():
    return "good morning"
print(greet())

good morning


In [42]:
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner()
def greet():
    return "good morning"
print(decor(greet))

    

GOOD MORNING


In [45]:
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner
@decor
def greet():
    return "good morning"
print(greet())

    

GOOD MORNING


In [47]:
ser1=pd.Series([1,2,3,4,5],['USA',"India","Canada","UK","Egypt"])
ser1

USA       1
India     2
Canada    3
UK        4
Egypt     5
dtype: int64

ser1['USA'] 

In [48]:
ser1['USA']

1

In [49]:
#access values using indexing
ser1[0]

1

In [50]:
#access values using indexing
ser1[0:3]

USA       1
India     2
Canada    3
dtype: int64

In [51]:
ser2=pd.Series([5,6,7,8],['USA','brazil',"Canada","UK"])
ser1+ser2


Canada    10.0
Egypt      NaN
India      NaN
UK        12.0
USA        6.0
brazil     NaN
dtype: float64

In [52]:
ser2

USA       5
brazil    6
Canada    7
UK        8
dtype: int64

In [54]:
#To create a new data in Series
ser2['china']="duplicate"
ser2

USA               5
brazil            6
Canada            7
UK                8
china     duplicate
dtype: object

In [55]:
ser2.drop('USA')

brazil            6
Canada            7
UK                8
china     duplicate
dtype: object

In [56]:
#DataFrame 
#pd.DataFrame(datas,row_abel,col_label)


In [58]:
df=pd.DataFrame(np.random.randn(5,4))

In [59]:
df

0         1         2         3
0  0.550042 -1.226305 -0.532725  1.496952
1  1.335467  0.239330 -0.084569  2.006973
2  0.806645 -0.394971  0.354501 -1.557049
3 -0.132081  0.480365  0.213638 -0.013645
4  0.268231  0.787668  0.977648 -0.140124

In [60]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df


W         X         Y         Z
A  0.932086  2.087193 -1.546238 -0.142790
B -0.195284 -0.331325 -1.608791 -0.310980
C  0.745213  0.777543  0.613028 -0.334343
D  0.597698 -0.385500 -1.287249  1.017780
E  0.892330  2.175195 -0.693797  0.001651

In [63]:
#to convert dictionary to DataFrame
d={'coll':[1,2],'col2':[3,4],'col3':[5,6]}
d

{'coll': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [65]:
df=pd.DataFrame(data=d)

In [66]:
df

coll  col2  col3
0     1     3     5
1     2     4     6

In [67]:
df=pd.DataFrame(d,["row1","row2"])
df

coll  col2  col3
row1     1     3     5
row2     2     4     6

In [68]:
df.index

Index(['row1', 'row2'], dtype='object')

In [69]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df


W         X         Y         Z
A -0.249172 -0.865281  0.294652 -2.046381
B  0.576735 -0.615973  1.757895  1.912074
C  1.276255 -0.077355 -2.226533  1.146554
D  0.609730 -0.491400 -1.359814 -0.445368
E  1.114749  0.533297 -1.483608 -0.902629

In [72]:
#column converts into row and viseversa
df.T

A         B         C         D         E
W -0.249172  0.576735  1.276255  0.609730  1.114749
X -0.865281 -0.615973 -0.077355 -0.491400  0.533297
Y  0.294652  1.757895 -2.226533 -1.359814 -1.483608
Z -2.046381  1.912074  1.146554 -0.445368 -0.902629

In [73]:
df.index #-->get all the rows name

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [75]:
df.columns  #-->get all the column name

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [76]:
type(df)

pandas.core.frame.DataFrame

In [77]:
df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [78]:
df.info() ---->to get information about DataFrame

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [80]:
df.values

array([[-0.24917185, -0.86528089,  0.29465185, -2.04638148],
       [ 0.57673462, -0.61597312,  1.75789506,  1.91207386],
       [ 1.27625462, -0.07735475, -2.22653337,  1.14655397],
       [ 0.60972964, -0.49140008, -1.3598137 , -0.44536833],
       [ 1.11474883,  0.5332971 , -1.48360805, -0.90262889]])

In [81]:
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['W', 'X', 'Y', 'Z'], dtype='object')]

In [82]:
df.ndim

2

In [83]:
df.size

20

In [84]:
#To access specific column in df
df

W         X         Y         Z
A -0.249172 -0.865281  0.294652 -2.046381
B  0.576735 -0.615973  1.757895  1.912074
C  1.276255 -0.077355 -2.226533  1.146554
D  0.609730 -0.491400 -1.359814 -0.445368
E  1.114749  0.533297 -1.483608 -0.902629

In [85]:
df['W']

A   -0.249172
B    0.576735
C    1.276255
D    0.609730
E    1.114749
Name: W, dtype: float64

In [86]:
type(df['W'])

pandas.core.series.Series

In [87]:
#To access multiple columns
df[['W','X','Y']]

W         X         Y
A -0.249172 -0.865281  0.294652
B  0.576735 -0.615973  1.757895
C  1.276255 -0.077355 -2.226533
D  0.609730 -0.491400 -1.359814
E  1.114749  0.533297 -1.483608

In [88]:
#To create new column
df['new']=df['W']+df['Y']
df

W         X         Y         Z       new
A -0.249172 -0.865281  0.294652 -2.046381  0.045480
B  0.576735 -0.615973  1.757895  1.912074  2.334630
C  1.276255 -0.077355 -2.226533  1.146554 -0.950279
D  0.609730 -0.491400 -1.359814 -0.445368 -0.750084
E  1.114749  0.533297 -1.483608 -0.902629 -0.368859

In [91]:
df.drop('new',axis=1)

W         X         Y         Z
A -0.249172 -0.865281  0.294652 -2.046381
B  0.576735 -0.615973  1.757895  1.912074
C  1.276255 -0.077355 -2.226533  1.146554
D  0.609730 -0.491400 -1.359814 -0.445368
E  1.114749  0.533297 -1.483608 -0.902629

In [93]:
df


W         X         Y         Z       new
A -0.249172 -0.865281  0.294652 -2.046381  0.045480
B  0.576735 -0.615973  1.757895  1.912074  2.334630
C  1.276255 -0.077355 -2.226533  1.146554 -0.950279
D  0.609730 -0.491400 -1.359814 -0.445368 -0.750084
E  1.114749  0.533297 -1.483608 -0.902629 -0.368859

In [ ]:
df.drop('new',axis=1,inplace=True)
df


In [101]:
df

W         X         Y         Z
A -0.249172 -0.865281  0.294652 -2.046381
B  0.576735 -0.615973  1.757895  1.912074
C  1.276255 -0.077355 -2.226533  1.146554
D  0.609730 -0.491400 -1.359814 -0.445368
E  1.114749  0.533297 -1.483608 -0.902629

In [1]:
#1.) Add anothjer row to this array
#row to be added = [12,23,45] 
#ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

#2.)Find the frequency of all element in the series
#se = pd.Series([1,1,1,2,2,2,2,3,3,3,4,4,5])

#3.)Reshape the series ser into a dataframe 
#ser = pd.Series(np.random.randint(1, 10, 35))

#4.)Find the positions of numbers that are multiples of 3 from ser
#ser = pd.Series(np.random.randint(1, 10, 10))

#5.) Join the two series
#ser1 = pd.Series(range(5))
#ser2 = pd.Series(list('abcde'))

#6.)Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.
#Sample Python dictionary data and list labels
#exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
#'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
#'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
#'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
#labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']